package com.saga.engine.enums;

public enum EventType {
    SAGA_STARTED,
    SAGA_COMPLETED,
    SAGA_FAILED,
    SAGA_COMPENSATING,
    SAGA_TIMED_OUT,
    STEP_STARTED,
    STEP_COMPLETED,
    STEP_FAILED,
    STEP_TIMED_OUT,
    STEP_SKIPPED,
    COMPENSATION_STARTED,
    COMPENSATION_COMPLETED,
    COMPENSATION_FAILED
}
